# Generated by Django 5.1.4 on 2026-05-21 10:00

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('format', models.CharField(choices=[('mp3', 'MP3'), ('aac', 'AAC'), ('ogg', 'OGG')], max_length=10)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'music_processingjob',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[users.validators.validate_title_word_count])),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('track_number', models.PositiveIntegerField(blank=True, null=True)),
                ('original_file', models.FileField(upload_to='tracks/original/', validators=[users.validators.validate_audio_file_size, users.validators.validate_audio_format])),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('transcoding_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'music_track',
            },
        ),
        migrations.CreateModel(
            name='TrackFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tracks/transcoded/')),
                ('format', models.CharField(choices=[('mp3', 'MP3'), ('aac', 'AAC'), ('ogg', 'OGG')], max_length=10)),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('codec', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'music_trackfile',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'music_genre',
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='name_not_empty')],
            },
        ),
    ]
