# Generated by Django 5.1.4 on 2026-05-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='releases.release'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='music.track'),
        ),
        migrations.AddField(
            model_name='trackfile',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_files', to='music.track'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.CheckConstraint(condition=models.Q(('transcoding_status__in', ['pending', 'processing', 'completed', 'failed'])), name='transcoding_status_choices'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__lte', 524288000)), name='file_size_limit'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'completed', 'failed'])), name='processingjob_status_choices'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('max_retries__lte', 5)), name='max_retries_limit'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('retries__lte', models.F('max_retries'))), name='retries_within_limit'),
        ),
        migrations.AddConstraint(
            model_name='trackfile',
            constraint=models.CheckConstraint(condition=models.Q(('format__in', ['mp3', 'aac', 'ogg'])), name='trackfile_format_choices'),
        ),
    ]
