# Generated by Django 5.1.4 on 2026-05-26 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='releases.release'),
        ),
    ]
