# Generated by Django 5.1.4 on 2026-05-21 10:00

import django.db.models.deletion
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[users.validators.validate_title_word_count])),
                ('description', models.TextField(blank=True, null=True)),
                ('release_type', models.CharField(choices=[('album', 'Album'), ('ep', 'EP'), ('single', 'Single')], default='album', max_length=10)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover_artwork', models.ImageField(blank=True, null=True, upload_to='cover_artwork/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='users.artistprofile')),
                ('genre', models.ManyToManyField(blank=True, related_name='releases', to='music.genre')),
            ],
            options={
                'db_table': 'releases_release',
                'constraints': [models.UniqueConstraint(fields=('artist', 'title'), name='unique_release_per_artist'), models.CheckConstraint(condition=models.Q(('release_type__in', ['album', 'ep', 'single'])), name='release_type_choices'), models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'private'])), name='release_visibility_choices')],
            },
        ),
    ]
